version: "3"
services:
  web:
    image: wordpress:latest
    ports:
      - 8080:80
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: password
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
